version: "3.8"

services:

  mysql:
    image: mysql:8.2.0
    container_name: mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - lara_custom

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/var/www/html/backend
    depends_on:
      - mysql
    networks:
      - lara_custom

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/backend
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - lara_custom

volumes:
  mysql:
    driver: local

networks:
  lara_custom:
